In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.insert(0, '..')

from src.data import fetch_yahoo_data, merge_yahoo_datasets, fetch_weather_data, compute_rolling_weather, merge_price_weather

save_path = 'C:/Users/roosd/Downloads/econometrie jaar 3/TIC/Spring2026-TIC'

Failed to read module file 'c:\Users\roosd\miniconda3\envs\TIC\Lib\re\_casefix.py' for module 're._casefix': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 895: character maps to <undefined>
Failed to read module file 'c:\Users\roosd\miniconda3\envs\TIC\Lib\pydoc_data\topics.py' for module 'pydoc_data.topics': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4651: character maps to <undefined>
Failed to read module file 'c:\Users\roosd\miniconda3\envs\TIC\Lib\urllib\parse.py' for module 'urllib.parse': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1980: character maps to <undefined>
Failed to read module file 'c:\Users\roosd\miniconda3\envs\TIC\Lib\functools.py' for module 'functools': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 301: character maps to <undefined>
Failed to read module file 'c:\Users\roosd\miniconda3\envs\TIC\Lib\shlex.py' for module 'shlex': UnicodeDecodeError
Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\roosd\AppData\Roaming\Python\Python311\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "c:\Users\roosd\miniconda3\envs\TIC\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1442: character maps to <undefined>

In [2]:
# Fetch corn and soybean ETF
fetch_yahoo_data('CORN', 'corn', save_path=save_path)
fetch_yahoo_data('SOYB', 'soybean', save_path=save_path)
fetch_yahoo_data('WEAT', 'wheat', save_path=save_path)

c:\Users\roosd\Downloads\econometrie jaar 3\TIC\Spring2026-TIC\Roos\src\data.py:20: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period='max', timeout=10)
[*********************100%***********************]  1 of 1 completed
c:\Users\roosd\Downloads\econometrie jaar 3\TIC\Spring2026-TIC\Roos\src\data.py:20: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period='max', timeout=10)
[*********************100%***********************]  1 of 1 completed
c:\Users\roosd\Downloads\econometrie jaar 3\TIC\Spring2026-TIC\Roos\src\data.py:20: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, period='max', timeout=10)
[*********************100%***********************]  1 of 1 completed

            close_wheat  high_wheat   low_wheat  open_wheat  volume_wheat
date
2011-09-19   122.849998  122.849998  122.849998  122.849998            20
2011-09-20   124.349998  124.349998  122.849998  123.400002           200
2011-09-21   121.150002  123.400002  121.150002  122.050003            60
2011-09-22   115.000000  118.550003  115.000000  118.550003           200
2011-09-23   117.800003  117.800003  116.400002  116.599998            60
...                 ...         ...         ...         ...           ...
2026-04-17    22.469999   22.549999   22.010000   22.430000       1334200
2026-04-20    22.750000   22.990000   22.510000   22.620001        519800
2026-04-21    23.160000   23.160000   22.660000   22.690001        701600
2026-04-22    22.860001   23.120001   22.840000   23.070000        640100
2026-04-23    23.410000   23.420000   22.889999   22.959999        607800

[3670 rows x 5 columns]

In [3]:
# merge yahoo datasets
merge_yahoo_datasets(['corn', 'soybean', 'wheat'], 'merged_corn_soybean_wheat', save_path=save_path)

,close_corn,high_corn,low_corn,open_corn,volume_corn,close_soybean,high_soybean,low_soybean,open_soybean,volume_soybean,close_wheat,high_wheat,low_wheat,open_wheat,volume_wheat
date,,,,,,,,,,,,,,,
2011-09-19,45.650002,45.919998,45.000000,45.459999,114300,24.549999,24.549999,24.549999,24.549999,100,122.849998,122.849998,122.849998,122.849998,20
2011-09-20,45.540001,46.720001,45.369999,46.110001,117200,25.080000,25.080000,24.660000,24.990000,1200,124.349998,124.349998,122.849998,123.400002,200
2011-09-21,44.799999,46.040001,44.750000,45.900002,83300,24.340000,25.110001,24.340000,24.959999,4400,121.150002,123.400002,121.150002,122.050003,60
2011-09-22,42.990002,44.669998,42.650002,43.959999,352500,24.000000,24.000000,24.000000,24.000000,100,115.000000,118.550003,115.000000,118.550003,200
2011-09-23,42.450001,43.389999,42.400002,42.990002,158800,23.000000,24.430000,23.000000,24.430000,300,117.800003,117.800003,116.400002,116.599998,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-04-17,17.950001,17.990000,17.719999,17.830000,1077800,24.520000,24.570000,24.260000,24.330000,287500,22.469999,22.549999,22.010000,22.430000,1334200
2026-04-20,18.080000,18.160000,17.930000,17.959999,590000,24.540001,24.590000,24.430000,24.490000,98900,22.750000,22.990000,22.510000,22.620001,519800
2026-04-21,18.180000,18.240000,18.110001,18.129999,475600,24.740000,24.780001,24.610001,24.610001,93500,23.160000,23.160000,22.660000,22.690001,701600
2026-04-22,18.209999,18.330000,18.190001,18.240000,547400,24.510000,24.750000,24.469999,24.750000,108700,22.860001,23.120001,22.840000,23.070000,640100
2026-04-23,18.280001,18.320000,18.180000,18.209999,438300,24.440001,24.490000,24.410000,24.480000,85100,23.410000,23.420000,22.889999,22.959999,607800

In [ ]:
# US Corn Belt

LOCATIONS_US = {
    "central_iowa": (42.0, -93.5),        # Heart of corn/soy production
    "central_illinois": (40.1, -89.4),     # Major corn/soy state
    "central_indiana": (40.0, -86.2),      # Eastern corn belt
}

# Brazil soy regions (optional, for soybean-specific weather)
LOCATIONS_BRAZIL = {
    "mato_grosso": (-12.6, -55.5),
    "parana":      (-24.0, -51.5),
    "rio_grande_sul": (-29.5, -53.0),   # <-- add this
}

# US wheat belt locations
LOCATIONS_WHEAT = {
    "kansas":       (38.5, -98.0),    # biggest HRW wheat state
    "oklahoma":     (35.5, -97.5),    # second biggest HRW
    "north_dakota": (47.0, -100.0),   # spring wheat
}
# split API call into 2 to prevent error from requesting too much data at once
weather_US = fetch_weather_data(
    locations={**LOCATIONS_US, **LOCATIONS_BRAZIL},
    start_date="2005-01-01",
    save_path="../data/weather_corn.csv",
)

weather_soy= fetch_weather_data(
    locations={**LOCATIONS_US, **LOCATIONS_BRAZIL},
    start_date="2005-01-01",
    save_path="../data/weather_soy.csv",
)

weather_wheat = fetch_weather_data(
    locations=LOCATIONS_WHEAT,
    start_date="2005-01-01",
    save_path="../data/weather_wheat.csv",
)

OpenMeteoRequestsError: failed to request 'https://archive-api.open-meteo.com/v1/archive': {'reason': 'Your API call requests too much data. Please reduce the number of variables, locations and/or weather models.', 'error': True}

In [4]:
# US Corn Belt

LOCATIONS_US = {
    "central_iowa": (42.0, -93.5),        # Heart of corn/soy production
    "central_illinois": (40.1, -89.4),     # Major corn/soy state
    "central_indiana": (40.0, -86.2),      # Eastern corn belt
}

# Brazil soy regions (optional, for soybean-specific weather)
LOCATIONS_BRAZIL = {
    "mato_grosso": (-12.6, -55.5),
    "parana":      (-24.0, -51.5),
    "rio_grande_sul": (-29.5, -53.0),   # <-- add this
}

# US wheat belt locations
LOCATIONS_WHEAT = {
    "kansas":       (38.5, -98.0),    # biggest HRW wheat state
    "oklahoma":     (35.5, -97.5),    # second biggest HRW
    "north_dakota": (47.0, -100.0),   # spring wheat
}

In [5]:
weather_wheat = fetch_weather_data(
    locations=LOCATIONS_WHEAT,
    start_date="2005-01-01",
    save_path="../data/weather_wheat.csv",
)

Processing 'kansas': 38.49°N, -98.06°W
Processing 'oklahoma': 35.47°N, -97.50°W
Processing 'north_dakota': 46.99°N, -99.94°W

Saved to: ../data/weather_wheat.csv

In [ ]:
# Then merge both weather files(use merge function!!)
import pandas as pd
weather_combined = pd.concat([weather_corn_soy, weather_wheat], axis=1)
weather_combined.to_csv("../data/weather_combined.csv")

In [ ]:
# Transform the data
weather_rolled = compute_rolling_weather(
    "../data/weather_with_wheat.csv",
    window=30,
    save_path="../data/weather_rolled_with_wheat.csv",
)

Window:          30 days
Input columns:   90
Output columns:  90
Date range:      2005-01-30 00:00:00 to 2026-03-28 00:00:00
Valid rows:      7728 / 7728
Saved to:        ../data/weather_rolled.csv

In [ ]:
# Merge weather and price data
df = merge_price_weather(
    "../data/merged_corn_soybean_wheat.csv",
    "../data/weather_rolled_with_wheat.csv",
    save_path="../data/full_dataset_with_wheat.csv",
)

Price columns:   10
Weather columns: 90
Merged shape:    (3652, 100)
Date range:      2011-09-19 00:00:00 to 2026-03-27 00:00:00
Missing values:  0
Saved to:        ../data/full_dataset.csv